
/**
 * Auth
 */
//登录
export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_REJECTED = 'SIGN_IN_REJECTED';
export const SIGN_IN_FULFILLED = 'SIGN_IN_FULFILLED';

//注册
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_REJECTED = 'SIGN_UP_REJECTED';
export const SIGN_UP_FULFILLED = 'SIGN_UP_FULFILLED';

//注销
export const SIGN_OUT = 'SIGN_OUT';

//自动登录失败
export const AUTH_FAIL = 'AUTH_FAIL';

//获取验证码
export const GET_VALID = 'GET_VALID';
export const GET_VALID_REJECTED = 'GET_VALID_REJECTED';
export const GET_VALID_FULFILLED = 'GET_VALID_FULFILLED';

//检测用户名是否存在

export const CHECK_USERNAME_IS_EXISTED = 'CHECK_USERNAME_IS_EXISTED';
export const CHECK_USERNAME_IS_EXISTED_REJECTED = 'CHECK_USERNAME_IS_EXISTED_REJECTED';
export const CHECK_USERNAME_IS_EXISTED_FULLFILLED = 'CHECK_USERNAME_IS_EXISTED_FULLFILLED';

//清楚认证state 中的msg
export const CLEAR_AUTH_MESSAGE = 'CLEAR_AUTH_MESSAGE';

/**
 * 好友 friends
 */
//获取当期用户所有的好友
export const FETCH_FRIENDS = 'FETCH_FRIENDS';
export const FETCH_FRIENDS_REJECTED = 'FETCH_FRIENDS_REJECTED';
export const FETCH_FRIENDS_FULFILLED = 'FETCH_FRIENDS_FULFILLED';

//查询某个用户信息
export const QUERY_FRIEND = 'QUERY_FRIEND';
export const QUERY_FRIEND_REJECTED = 'QUERY_FRIEND_REJECTED';
export const QUERY_FRIEND_FULFILLED = 'QUERY_FRIEND_FULFILLED';

//添加好友
export const ADD_FRIEND = 'ADD_FRIEND';
export const ADD_FRIEND_REJECTED = 'ADD_FRIEND_REJECTED';
export const ADD_FRIEND_FULFILLED = 'ADD_FRIEND_FULFILLED';

//更新信息好友
export const UPDATE_FRIEND_REJECTED = 'UPDATE_FRIEND_REJECTED';
export const UPDATE_FRIEND_FULFILLED = 'UPDATE_FRIEND_FULFILLED';

//删除好友
export const DELETE_FRIEND_REJECTED = 'DELETE_FRIEND_REJECTED';
export const DELETE_FRIEND_FULFILLED = 'DELETE_FRIEND_FULFILLED';

/**
 * 信息 messages
 */
//抓取所有信息列表
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const FETCH_MESSAGES_REJECTED = 'FETCH_MESSAGES_REJECTED';
export const FETCH_MESSAGES_FULFILLED = 'FETCH_MESSAGES_FULFILLED';

//新建消息 、添加信息
export const POST_MESSAGE_REJECTED = 'POST_MESSAGE_REJECTED';
export const POST_MESSAGE_FULFILLED = 'POST_MESSAGE_FULFILLED';

//接受消息
export const RECEIVE_MESSAGE_FULFILLED = 'RECEIVE_MESSAGE_FULFILLED';

//删除信息
export const DELETE_MESSAGE_REJECTED = 'DELETE_MESSAGE_REJECTED';
export const DELETE_MESSAGE_FULFILLED = 'DELETE_MESSAGE_FULFILLED';

//nav 
export const LEAVE_NAV = 'LEAVE_NAV';  
