//验证码相关
exports.SEND_CODE_FAIL = 'SEND_CODE_FAIL';
exports.SAVE_CODE_FAIL = 'SAVE_CODE_FAIL';
exports.SAVE_CODE_SUCCESS = 'SAVE_CODE_SUCCESS';

exports.CODE_EXPIRED = 'CODE_EXPIRED';
exports.CODE_NOT_FIND = 'CODE_NOT_FIND';
exports.CODE_NOT_EQUAL = 'CODE_NOT_EQUAL';
exports.CODE_VALID_SUCCESS = 'CODE_VALID_SUCCESS';

//用户相关
exports.USER_NOT_EXISTED = 'USER_NOT_EXISTED';
exports.USER_ALREADY_EXISTED = 'USER_ALREADY_EXISTED';
exports.USER_AUTH_FAIL = 'USER_AUTH_FAIL';
exports.USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
exports.USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
exports.USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
exports.USER_UPDATE_LETESTMESSAGE_FAIL = 'USER_UPDATE_LETESTMESSAGE_FAIL';
exports.USER_UPDATE_LETESTMESSAGE_SUCCESS = 'USER_UPDATE_LETESTMESSAGE_SUCCESS';
//TOKEN相关
exports.TOKEN_EXPIRED = 'TOKEN_EXPIRED'; 
exports.TOKEN_AUTHENTICATION_FAIL = 'TOKEN_AUTHENTICATION_FAIL'; 
exports.TOKEN_NOT_EXISTED = 'TOKEN_NOT_EXISTED'; 

//chat eventName 相关
exports.POST_MESSAGE = 'POST_MESSAGE';
exports.RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
exports.ADD_FRIEND_REQUEST = 'ADD_FRIEND_REQUEST';
exports.ADD_FRIEND_FAIL = 'ADD_FRIEND_FAIL';
exports.ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS';
exports.SAVE_FRIEND_FAIL = 'SAVE_FRIEND_FAIL';
exports.SAVE_FRIEND_SUCCESS = 'SAVE_FRIEND_SUCCESS';
exports.FRIEND_IS_OFFLINE = 'FRIEND_IS_OFFLINE';
exports.RECEIVE_ADD_FRIEND_REQUEST = 'RECEIVE_ADD_FRIEND_REQUEST';
exports.CONFIRM_ADD_FRIEND_REQUEST = 'CONFIRM_ADD_FRIEND_REQUEST';
exports.RECEIVE_CONFIRM_ADD_FRIEND_REQUEST = 'RECEIVE_CONFIRM_ADD_FRIEND_REQUEST';
exports.REFUSE_ADD_FRIEND_REQUEST = 'REFUSE_ADD_FRIEND_REQUEST';
exports.RECEIVE_REFUSE_ADD_FRIEND_REQUEST = 'RECEIVE_REFUSE_ADD_FRIEND_REQUEST';